include: package:extra_pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # This rule has just too many false-positives...
    close_sinks: false