name: tar
description: Memory-efficient, streaming implementation of the tar file format
version: 0.2.0-dev
repository: https://github.com/simolus3/tar/

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  charcode: ^1.2.0-nullsafety
  chunked_stream: ^1.3.0-nullsafety.0
  meta: ^1.3.0-nullsafety.6
  synchronized: ^3.0.0-nullsafety.1
  typed_data: ^1.3.0-nullsafety.5

dev_dependencies:
  extra_pedantic: ^1.2.0
  test: ^1.16.0-nullsafety
