name: tar
description: Memory-efficient, streaming implementation of the tar file format
version: 0.1.0-nullsafety.0
repository: https://github.com/simolus3/tar/

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  synchronized: ^3.0.0-nullsafety.1
  charcode: ^1.2.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
